# Generated by Django 4.1.5 on 2023-02-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='collection',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='departmentname',
            new_name='collection_name',
        ),
    ]
