# Generated by Django 4.1.5 on 2023-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0002_rename_department_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deptid',
            new_name='colid',
        ),
    ]
