# Generated by Django 4.1.5 on 2023-02-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0003_rename_deptid_employee_colid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='workflow',
        ),
    ]
