# Generated by Django 4.1.5 on 2023-02-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0004_rename_employee_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='empname',
            new_name='workflow_name',
        ),
    ]
