# Generated by Django 4.1.5 on 2023-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0005_rename_empname_workflow_workflow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_ad_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
