# Generated by Django 4.1.5 on 2023-02-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0006_collection_collection_ad_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='age',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='contactno',
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
