# Generated by Django 4.1.5 on 2023-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0007_remove_workflow_address_remove_workflow_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
                ('workflow_name', models.CharField(max_length=100)),
            ],
        ),
    ]
