# Generated by Django 4.1.5 on 2023-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayx', '0008_decomrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='decomrequest',
            name='workflow_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
